version: '1.0'
stages:
- checkout
- build
- approval
- push
steps:
  main_clone:
    title: Cloning cf auto repository...
    type: git-clone
    stage: checkout
    repo: https://github.com/Meenan21/cf_automation.git
    revision: 'master'
    git: github
    
  source_clone:
    title: Cloning app source repository...
    type: git-clone
    stage: checkout
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_BRANCH}}
    git: github
    
  build:
    stage: build
    title: "Building production image"
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    working_directory: ./
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    dockerfile: Dockerfile
    build_arguments:
    - CF_REVISION=${{CF_REVISION}}
    - CF_BRANCH=${{CF_BRANCH}}
    #- user=*****@sample.com
    #environment:
      #- PORT=4444
      #- TEST=test
    retry:
      maxAttempts: 3
      delay: 5
    when:
      steps:
      - name: main_clone
        on:
        - success
      - name: source_clone
        on:
        - success 
        
  waitForInputBeforePushImage:
    stage: approval
    type: pending-approval
    title: Image push to Registry?
    timeout:
      duration: 2
      finalState: denied      
    
  push_to_my_registry:
    stage: push
    title: 'Pushing image to registry'
    type: push
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    registry: dockerhub
    candidate: ${{build}}
    tag: latest
    when:
      steps:
      - name: build
        on:
        - success
      - name: waitForInputBeforePushImage
        on:
        - approved
